#!/bin/sh

PATH=$HOME/bin:${HOME}/osb/bin:/usr/local/bin:/usr/contrib/bin:/bin:/usr/bin

OSB=/users/phil/osb
export OSB
cd ${OSB}/mudlib

today=`date +%j`

touch players/mateese/.fnase_new

cp FILELIST FILELIST.$today

find * ! \( -name ftp -prune \) -type f -newer players/mateese/.fnase_to_touch -exec tar uvf ${OSB}/tmp/osb$today.tar {} \;

rm FILELIST.$today

mv players/mateese/.fnase_new players/mateese/.fnase_to_touch

exit 0
