repos:
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
    entry: cz check
    args: [--rev-range, origin/master..HEAD]
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.42.1
