#ifndef _SECURE_VERSION_
#define _SECURE_VERSION_ 1

/*--------------------------------------------------------------------------
 * /sys/secure/version.h -- Mudlib version and revision numbers.
 *
 * Copyright (C) 1997 by One Step Beyond.
 * All Rights Reserved.
 * Permission granted for non-commercial use.
 *
 * DO NOT EDIT THIS FILE unless you really know what you do!
 *--------------------------------------------------------------------------
 * This file is evaluated by some programs and must stick to the given
 * format.
 */

/* The major version of the mudlib */
#define LIBVERSION 0

/* The minor version of the mudlib */
#define LIBREVISION 5

/* The current level within prcs. Increment this level with every change
 * to LIBVERSION or LIBREVISION.
 */
#define LIBPRCSLEVEL 5

/* The current patchlevel, incremented at every checkin.
 * The next line is magic: */
/* $Format: "#define LIBPATCHLEVEL $ProjectMinorVersion$"$ */
#define LIBPATCHLEVEL 5

#endif /* _SECURE_VERSION_ */

